### ISSUE TITLE
Markbot Image Naming Issue

### ISSUE THREAD

**Issue by prim0062** [prim0062/production-prepping-issue#1]
If I rename them to follow proper naming conventions, Markbot can't find the images anymore, and tells me they are missing. Markbot is only looking for the original names, but is also punishing if they're not following standards.
@charlie-quinn

**Comment by charlie-quinn** [comment]
@prim0062 ah, I see the issue.

Markbot wants you to keep the original `untouched` asset files named as they were. Try submitting the assignment this way and see if Markbot accepts it. 🤖

**Comment by prim0062** [comment]
@charlie-quinn I've just tried submitting with the original names. Even re-downloaded the project and put those originals in, but Markbot says they don't follow the naming conventions. Image below.
![markbot](https://user-images.githubusercontent.com/43246445/65566614-6a30ab00-df21-11e9-9fd1-cdc85f7ed0e7.png)

**Comment by charlie-quinn** [comment]
@prim0062 I downloaded your project and successfully submitted it in Markbot without changes. 🤖 
Try this out:
- [ ] reinstall Markbot
- [ ] try submitting your assignment again with the original assets

If this doesn't fix it then we'll take another look in class this week. 👀

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
