### ISSUE TITLE
File naming issue

### ISSUE THREAD

**Issue by prim0062** [prim0062/production-prepping-issue#2]
I'm currently having an issue with Markbot. I've completed the exercise 

Production prepping & compression, but Markbot keeps suggesting the asset file names don't follow the naming conventions. When I rename the images to follow conventions, Markbot now says the files are missing, and can only be found if I return them to their original, unconventional names. I've attached two images of my situation, one for both of Markbot's responses.
@charlie-quinn

This is the original file names:

![original names](https://user-images.githubusercontent.com/43246445/69917489-ad812b80-1434-11ea-8329-f62092a808de.png)

This is when I rename the files to follow conventions:

![renamed](https://user-images.githubusercontent.com/43246445/69917490-ad812b80-1434-11ea-99dc-4c43b88237db.png)

**Comment by charlie-quinn** [comment]
Markbot is correct, you aren't following proper file naming conventions!

You can find more information on [file naming conventions here.](https://learn-the-web.algonquindesign.ca/topics/naming-paths-cheat-sheet/)

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by prim0062** [comment]
In this repo, yes the file names are unchanged. When I rename them to follow conventions like so
![12c3072fb6b436bdf035302175dd1160](https://user-images.githubusercontent.com/43246445/70073214-7478c080-15c6-11ea-812f-c76db4b9bf93.png)

This is the response I get from Markbot
![69917490-ad812b80-1434-11ea-99dc-4c43b88237db](https://user-images.githubusercontent.com/43246445/70073255-82c6dc80-15c6-11ea-9cc4-e483c9bf081e.png)

**Comment by charlie-quinn** [comment]
Alright, let's take a look in class together then. Might be a Markbot bug.
